# Generated by Django 4.1 on 2023-06-26 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=40)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('time_slot_per_patient_time', models.CharField(max_length=20)),
                ('first_consultation_fee', models.CharField(max_length=20)),
                ('followup_consultation_fee', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='qualification_name', max_length=200)),
                ('institute_name', models.CharField(max_length=200)),
                ('passing_year', models.DateField()),
                ('userid', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeDoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.CharField(max_length=3)),
                ('office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.office')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.specialty')),
                ('userid', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='first_name', max_length=30)),
                ('lastname', models.CharField(db_column='last_name', max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=8)),
                ('practicing_year', models.DateField(null=True)),
                ('professional_statement', models.TextField(null=True)),
                ('is_password_send', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probable_start_time', models.TimeField()),
                ('actual_end_time', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.office')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
    ]
