# Generated by Django 4.1 on 2023-06-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='is_password_send',
        ),
    ]
