# Generated by Django 4.1 on 2023-06-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorinfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='is_password_sent',
            field=models.BooleanField(default=False),
        ),
    ]
