# Generated by Django 4.1 on 2023-06-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorinfo_is_password_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='officedoctoravailability',
            name='is_available',
        ),
    ]
