# Generated by Django 4.1 on 2023-06-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0007_alter_office_address1_alter_office_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=15, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('userid', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='office_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo'),
        ),
        migrations.AlterField(
            model_name='office',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='address2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='first_consultation_fee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='followup_consultation_fee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='state',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='time_slot_per_patient_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institute_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(db_column='qualification_name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='passing_year',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='OfficeDoctorAvailability',
        ),
    ]
