# Generated by Django 4.1 on 2023-06-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctoravailability_remove_appointment_office_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo'),
        ),
    ]
