# Generated by Django 4.1 on 2023-07-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_appointment_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_of_unavailability',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Not-Visit', max_length=15),
        ),
    ]
